name: Check linting

on:
    push:
        branches: [ "development" ]

jobs:

    check-link:
        name: Check linting

        runs-on: windows-latest

        steps:
        
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: arduino/arduino-lint-action
          uses: arduino/arduino-lint-action@v1.0.2